version: '4.28'
services:
  postgres:
    image: postgres:16.2
    ports:
      - ${POSTGRES_HOST_PORT:-5432}:5432
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    env_file: ./postgres.env
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    env_file: ./zookeeper.env
    ports:
      - ${ZOOKEEPER_HOST_PORT:-2181}:2181
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_HOST_PORT:-29092}:29092
    env_file: ./kafka.env
  elk:
    image: sebp/elk:8.11.1
    ports:
      - ${ELK_KIBANA_UI_HOST_PORT:-5601}:5601
      - ${ELK_ELASTIC_JSON_HOST_PORT:-9200}:9200
      - ${ELK_LOGSTASH_HOST_PORT:-5044}:5044
      - ${ELK_LOGSTASH_INPUT_HOST_PORT:-5030}:5030 # input from services
    env_file: ./elk.env
    volumes:
      - ${ELK_KIBANA_CONFIG_VOLUME}:/opt/kibana/config/kibana.yml
      - ${ELK_LOGSTASH_SERVICES_CONFIG_VOLUMES}:/etc/logstash/conf.d/101-services.conf